name: bertnado
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - crested
      - anndata
      - click
      - crested
      - datasets
      - loguru
      - matplotlib
      - pandas
      - peft
      - pytest
      - scikit-learn
      - seaborn
      - transformers
      - wandb